### PR TITLE
Add the ability to pass args to a query

### PR DESCRIPTION
**Pull request by cndreisbach**
Datomic queries can take multiple arguments, but currently we are only sending the db alias of the database we pass in. This is a first stab at making that more flexible. I wonder if we would be better served by changing the way the query function works altogether.

### CODE REVIEW

**Comment by cndreisbach** [comment]
BTW, if you want to brainstorm on this tomorrow (Friday), I'd love to do that.

**Comment by cldwalker** [comment]
brainstorming tomorrow would be great

**Comment by cndreisbach** [comment]
Fixed this to match our discussion and added tests.

**Comment by cldwalker** [comment]
Nice! Will merge and release soon.

**Pull request merged**
